### ISSUE TITLE
Reorganize the directory structure in the repo

### ISSUE THREAD

**Issue by rkojcev** [ros-industrial-attic/fermi#20]
Reorganize the directory structure in the github repo putting the plugin into the root of the repo.

Considering the pre-configured MoveIt packages for the robots, where we should put those directories?

If we put the source code in the root of the repo then it could be little bit messy because we will have the code structure of the plugin and the directories of the pre-configured robots? Should we place pre-configured robots in separate repo?

**Comment by shaun-edwards** [comment]
We want to put the package directories in the root of the repo...not the source code.  The pre-configured robot packages can go in the root of the repo as well.  Here is an [example](https://github.com/ros-industrial/motoman).
