### ISSUE TITLE
MoveIt group hardcoded to "manipulator"

### ISSUE THREAD

**Issue by rkojcev** [ros-industrial-attic/fermi#27]
The MoveIt group is hardcoded as "manipulator". Dynamically load the group name from ROS parameter service or through the GUI.

**Comment by madratman** [comment]
Hi, I am new here. 
On doing `$ roslaunch fermi_blending_cell_moveit_config moveit_planning_execution.launch`, I am getting 

`started core service [/rosout]
process[industrial_robot_simulator-2]: started with pid [14480]`

...

`[ INFO] [1427053093.770612603]: compiled against OGRE version 1.7.4 (Cthugha)
process[mongo_wrapper_ros_ratnesh_Inspiron_N5010_14438_8639572172963113131-7]: started with pid [14569]
[ERROR] [1427053094.360788770]: Group 'manipulator' for end-effector 'blend_tool_tip' cannot be its own parent
[ WARN] [1427053094.361046157]: Could not identify parent group for end-effector 'blend_tool_tip'`
...
`[ INFO] [1427053095.181158914]: No root joint specified. Assuming fixed joint
[ERROR] [1427053096.699333949]: Group 'manipulator' for end-effector 'blend_tool_tip' cannot be its own parent
[ WARN] [1427053096.699754315]: Could not identify parent group for end-effector 'blend_tool_tip'
[ INFO] [1427053097.332527210]: Publishing maintained planning scene on 'monitored_planning_scene'
[ INFO] [1427053097.352831892]: MoveGroup debug mode is OFF
Starting context monitors...`
...
`All is well! Everyone is happy! You can start planning now!`

`[ INFO] [1427053108.424993298]: Constructor created;
[ INFO] [1427053108.465591023]: Loading robot model 'sia20d_workspace'...
[ INFO] [1427053108.465919295]: No root joint specified. Assuming fixed joint
[ERROR] [1427053109.647904781]: Group 'manipulator' for end-effector 'blend_tool_tip' cannot be its own parent
[ WARN] [1427053109.648106726]: Could not identify parent group for end-effector 'blend_tool_tip'
[ INFO] [1427053110.233140995]: Loading robot model 'sia20d_workspace'...
[ INFO] [1427053110.233338447]: No root joint specified. Assuming fixed joint
[ERROR] [1427053111.394026139]: Group 'manipulator' for end-effector 'blend_tool_tip' cannot be its own parent
[ WARN] [1427053111.394243255]: Could not identify parent group for end-effector 'blend_tool_tip'
[ INFO] [1427053112.276268927]: Ready to take MoveGroup commands for group manipulator.`

Is this related to this? Can you guide so as to how can it be solved? I'd like to start contributing.
