### ISSUE TITLE
Arrows names not readable

### ISSUE THREAD

**Issue by VictorLamoine** [ros-industrial-attic/fermi#30]
The label of the arrow is far away from the arrow itself making it hard to recognize what text belongs to which arrow.

![arrow](https://cloud.githubusercontent.com/assets/5566160/5379124/3b9504b2-808f-11e4-838a-b59144a3aa79.png)

**Comment by rkojcev** [comment]
That is true. I think this is an rviz problem in implementation. I have tried to change it while ago but I didnt find any possible way.

Maybe some of the other guys who has found solution could ping :)

**Comment by rkojcev** [comment]
closing this
