### ISSUE TITLE
catkin make error

### ISSUE THREAD

**Issue by james2254** [ros-industrial-attic/fermi#34]
When I run catkin_make in the terminal , there are some errors:

```
In file included from /usr/include/qt4/QtCore/qvariant.h:46:0,
                 from /usr/include/qt4/QtCore/QVariant:1,
                 from /home/james/catkin_ws/build/fermi-indigo-devel/moveit_cartesian_plan_plugin/ui_path_planning_widget.h:12,
                 from /home/james/catkin_ws/src/fermi-indigo-devel/moveit_cartesian_plan_plugin/include/moveit_cartesian_plan_plugin/widgets/path_planning_widget.h:14,
                 from /home/james/catkin_ws/src/fermi-indigo-devel/moveit_cartesian_plan_plugin/src/widgets/path_planning_widget.cpp:1:
/usr/include/qt4/QtCore/qbytearray.h:598:28: note: QDataStream& operator>>(QDataStream&, QByteArray&)
 Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QByteArray &);
                            ^
/usr/include/qt4/QtCore/qbytearray.h:598:28: note:   no known conversion for argument 1 from ‘YAML::Node’ to ‘QDataStream&’
make[2]: *** [fermi-indigo-devel/moveit_cartesian_plan_plugin/CMakeFiles/moveit_cartesian_plan_plugin.dir/src/widgets/path_planning_widget.cpp.o] 错误 1
make[1]: *** [fermi-indigo-devel/moveit_cartesian_plan_plugin/CMakeFiles/moveit_cartesian_plan_plugin.dir/all] 错误 2
make: *** [all] 错误 2
Invoking "make -j4 -l4" failed
james@james-23-g131cn:~/catkin_ws$ 
```

What's worry with it? Thank you very much.

**Comment by rkojcev** [comment]
Hi @james2254 , I made a new pull request that i will leave it for today in case anyone wants to review. Tomorrow I will merge it to the indigo-devel branch.

Can you please try the indigo-devel branch again? I just made few changes that hopefully resolve the yaml and Qt issue. 

Let me know if you bump into any problems

**Comment by rkojcev** [comment]
@james2254  can you try if it compiles now?

**Comment by james2254** [comment]
Thank you very much! It works well! @rkojcev

**Comment by james2254** [comment]
Hi @rkojcev ，there is a error in fermi_irb2400 package.
When I run `roslaunch fermi_irb2400_moveit_config moveit_planning_execution.launch` in the terminal ,it doesn't work.

```
py", line 312, in resolve_args
    resolved = _resolve_args(resolved, context, resolve_anon, commands)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 325, in _resolve_args
    resolved = commands[command](resolved, a, args, context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 141, in _find
    source_path_to_packages=source_path_to_packages)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 184, in _find_executable
    full_path = _get_executable_path(rp.get_path(args[0]), path)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 200, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
ResourceNotFound: abb_common
ROS path [0]=/opt/ros/indigo/share/ros
ROS path [1]=/home/james/catkin_ws1/src
ROS path [2]=/home/james/catkin_ws/src
ROS path [3]=/opt/ros/indigo/share
ROS path [4]=/opt/ros/indigo/stacks
```

**Comment by gavanderhoorn** [comment]
The `abb_common` package has long been deprecated, and was removed from the `abb` repository in ros-industrial/abb#76.

In this case I think the relevant files can be found in `abb_irb2400_support`.

**Comment by james2254** [comment]
Can it be applied to abb irb120？

**Comment by rkojcev** [comment]
Hi @james2254 

The plugin can be applied to any robot. The packages of the different robots included here are just given as an example, in which the plugin is loaded automatically. They are taken from the default robot packages in the time of creation of the plugin, therefore they might be outdated, just to give the user an example and fast start up to test the plugin.

In order to load the plugin in the robot you can follow the following [tutorial](http://wiki.ros.org/moveit_cartesian_plan_plugin)

**Comment by rkojcev** [comment]
@james2254 did everything worked out fine? So i can close this issue :)

**Comment by james2254** [comment]
Yes， thank you very much
