### ISSUE TITLE
Enabling Setting Cartesian Impedance gui

### ISSUE THREAD

**Issue by rkojcev** [ros-industrial-attic/fermi#37]
@shaun-edwards, @gavanderhoorn, @davetcoleman 
Would this be of interest to expand this already existing plugin to enable setting Cartesian Impedance parameters and Force Control?

It might be nice to test the messages and execution of paths with Cartesian Impedance using this plugin...

If yes we might create a new branch that utilizes this functionalities...

**Comment by shaun-edwards** [comment]
I'd be supportive of this, but we should maintain the current functionality and allow specifying a path with and without impedance control.

**Comment by rkojcev** [comment]
work in progress [here](https://github.com/rkojcev/fermi/tree/indigo-devel-impedance). Once tested on the real robot I will make pull request.

I have also created a new branch indigo-devel-impedance where I will make my pull request.

**Comment by rkojcev** [comment]
I have modified fermi for allowing setting Impedance and Force Ctrl via the gui, please have a look at #38
