### ISSUE TITLE
Incomplete Path Planning

### ISSUE THREAD

**Issue by mat-l** [ros-industrial-attic/fermi#39]
Hello all, 
at first, thank you for developing this Plug In! It's very convenient for me. 
Although I have a little issue with the success ratio. The first time I execute the path it works just fine but every time after it crashes and just completes about one third of the way. (Move to Home as well as Execute Cartesian Path). After restarting RViz it works again for one time.
I use the iiwa robot from ROS Industrial.
Do you have an idea what is going wrong here?

Also is there a way to set the planning library used manually?
And one last thing: Are there any options to differ between LIN and PTP movements using the path planning tool?

Thank you

**Comment by rkojcev** [comment]
Hi @mat-l,

> The first time I execute the path it works just fine but every time after it crashes and just completes about one-third of the way. (Move to Home as well as Execute Cartesian Path). After restarting RViz it works again for one time.
> I use the iiwa robot from ROS-Industrial.
> Do you have an idea what is going wrong here?

Are you using the path planner in simulation (URDF model) or using it with the real robot? If using it in simulation, I had this experience when I used the default move it path planning. Which exact model are you using? Can you send me the link to your move it packages?

> Also is there a way to set the planning library used manually?

Yes, you can define that in the launch files. For example, I have used this plugin with the iiwa R800 and [trac_ik_lib](http://wiki.ros.org/trac_ik_lib).

> And one last thing: Are there any options to differ between LIN and PTP movements using the path planning tool?

The goal of this plugin is to be robot agnostic, so the plugin itself it does not differentiate between PTP or LIN motions. In this case is up to the iiwa driver and user to select when a motion is executed as PTP or LIN.

**Comment by mat-l** [comment]
I was able to solve the problem by using the trac_ik_lib as you suggested.
Thanks for youre help.
