### ISSUE TITLE
Melodic migration

### ISSUE THREAD

**Issue by ahcorde** [ros-industrial-attic/fermi#47]
In case you consider relevant I have made some changes to make it work with melodic

https://github.com/ahcorde/fermi/tree/melodic-devel

**Comment by jrgnicho** [comment]
@ahcorde thanks, could you create a PR?

**Comment by ahcorde** [comment]
can you create the branch `melodic-devel`? otherwise I cannot create the PR

**Comment by rkojcev** [comment]
@ahcorde and @jrgnicho I have created the melodic-devel branch
