### ISSUE TITLE
Usability - 3D Waypoint add/delete/modify

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-attic/fermi#5]
Suggested improvements for graphical adding/deleting/modification of waypoints
- [ ] The cube marker is difficult to use, we may consider doing away with it.  It currently does not allow you to rotate the cube, so added waypoints are always initiated in the default orientation.  We may want to consider replacing the cube with the arrow waypoint marker (maybe a different color).
- [ ] Marker appearing/disappearing
  - [ ] "Selecting" the cube interactive marker hides all of the markers.  It would be best if this did not occur
  - [ ] Utilizing the "Fine adjustment" menu option of the waypoint results in hiding _all_ waypoints when the marker is selected.  The pose/orientation marker is actually very good for modifying the waypoint if the waypoint remained visible (adding it to the cube marker may make it more usable).
- [ ] Unreachable waypoints should be identified in the visualization (different color?).  MoveIt can determine if a point is reachable by performing IK.  Note: The point may still be unreachable in a cartesian manor, but this is another issue.
- [ ] Duplicate waypoint method.  There should be a way to duplicate a waypoint when adding.
- [ ] Insert waypoint method.  Waypoints are currently ordered by when they are created.  This makes it impossible to add a waypoint in the middle of a path.

**Comment by rkojcev** [comment]
Improvements completed from this list
- [x] The cube marker is difficult to use, we may consider doing away with it.  It currently does not allow you to rotate the cube, so added waypoints are always initiated in the default orientation.  We may want to consider replacing the cube with the arrow waypoint marker (maybe a different color).
- [x] Marker appearing/disappearing
  - [x] "Selecting" the cube interactive marker hides all of the markers.  It would be best if this did not occur
  - [x] Utilizing the "Fine adjustment" menu option of the waypoint results in hiding _all_ waypoints when the marker is selected.  The pose/orientation marker is actually very good for modifying the waypoint if the waypoint remained visible (adding it to the cube marker may make it more usable).
- [x] Unreachable waypoints should be identified in the visualization (different color?).  MoveIt can determine if a point is reachable by performing IK.  Note: The point may still be unreachable in a cartesian manor, but this is another issue.
- [ ] Duplicate waypoint method.  There should be a way to duplicate a waypoint when adding.
- [ ] Insert waypoint method.  Waypoints are currently ordered by when they are created.  This makes it impossible to add a waypoint in the middle of a path.

**Comment by rkojcev** [comment]
Regarding this issue is it fine to close?

**Comment by shaun-edwards** [comment]
@rkojcev, I wouldn't close this until all the boxes can be checked....or you could close it and create separate issues for the remaining items.

**Comment by rkojcev** [comment]
I think closing it and making each of the unchecked boxes separate issue will be better for discussion about each of these improvements.
