### ISSUE TITLE
Support for Kinetic?

### ISSUE THREAD

**Issue by srini196** [ros-industrial-attic/fermi#51]
Is there an available version or ongoing effort to make this repo available in ROS Kinetic? Neither the indigo nor the melodic branch compile for me.

**Comment by srini196** [comment]
https://github.com/smith-doug/fermi possible that this works

**Comment by rkojcev** [comment]
Hi @srini196 I have not tested this plugin in kinetic, I have indeed tested and ported it back for melodic and worked fine with me (also tested on some real robots). If someone made it for kinetic it would be nice to include also that here.

Have a look at this [PR for melodic port](https://github.com/ros-industrial-consortium/fermi/pull/50)
