### ISSUE TITLE
Consider name change for Rviz panel

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-attic/fermi#7]
The Rviz panel name is "AddWayPoint".  We should consider updating the name to the proprer naming convention (i.e. Add Way Point) or giving it a more appropriate name since it does more than just add waypoints at this stage.

**Comment by rkojcev** [comment]
changed the name to: MoveIt Cartesian Path Planner

**Comment by gavanderhoorn** [comment]
> changed the name to: MoveIt Cartesian Path Planner

To me this sounds like you are adding a planner to MoveIt: one that does Cartesian planning. Perhaps add a noun to more precisely convey the fact that this is 'just' an RViz panel UI to the existing planning?

**Comment by rkojcev** [comment]
Good suggestion, thanks

**Comment by gavanderhoorn** [comment]
The RViz plugin is still called "MoveIt Cartesian Path Planner" right? We don't feel this is a misnomer anymore?

**Comment by rkojcev** [comment]
I have renamed the plugin to: Cartesian Path Planner MoveIt Plug-in.
Is this name more appropriate?

**Comment by gavanderhoorn** [comment]
Well, the name still does not reflect the fact that it is 'only' an RViz plugin, which provides UI to interact _with_ the existing Cartesian planning support in MoveIt.

As far as I know, you haven't implemented a new MoveIt Cartesian planner plugin, am I right?

**Comment by rkojcev** [comment]
No this plugin uses the existing MoveIt Cartesian plugin. But it also uses RQT so its not only RViz...
How about renaming it into: Cartesian Path Planner MoveIt UI?

**Comment by rkojcev** [comment]
I meant: UI for MoveIt Cartesian Path Planning

**Comment by gavanderhoorn** [comment]
Well, naming is rather personal :). Maybe make a list with some alternatives. My suggestion: _MoveItCartesianPlanning_.

Perhaps even don't include the MoveIt prefix, as the 'official' _MotionPlanning_ moveit rviz plugin also does not have it.

**Comment by rkojcev** [comment]
:D I have always been bad name giver :) CartesianPlanning sounds nice. Any other suggestions from the others are welcomed!!

**Comment by rkojcev** [comment]
After chatting with @shaun-edwards today we decided to rename the package and the panel as is in the [ROS Wiki tutorials for the plugin](http://wiki.ros.org/moveit_cartesian_plan_plugin).

**Comment by rkojcev** [comment]
Changed the name of the package to moveit_cartesian_plan_plugin and the panel to MoveIt Cartesian Plan Plug-in. The master branch is updated with this change.
