### ISSUE TITLE
Usability - Add waypoint GUI fields confusing

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-attic/fermi#8]
When selecting waypoint from the tree, I initially thought the waypoint fields (in the section below the tree) would be populated with the selected waypoint.  That did not occur.  To modify an existing point, I had to work through the tree (which isn't so bad).  When adding a point, I utilized the fields below.  It seems to me that there are two different ways to do what feels like the same thing.

**Comment by rkojcev** [comment]
Changed the UI so it refers that the panel is only for adding new way-point. Should I close this issue?
